baseURL = "https://shahrazad.fun"
title = "Shahrazad"
copyright = ""
paginate = 5
languageCode = "en"
defaultContentLanguage = "en"
hasCJKLanguage = true
enableInlineShortcodes = true
enableEmoji = true
ignoreErrors = ["error-remote-getjson"]
disableHugoGeneratorInject = true
version = "hugo_extended_0.114.0_darwin-universal"

[outputs]
home = ["HTML", "JSON", "RSS"]

[taxonomies]
category = "categories"
tag = "tags"
series = "series"

[markup]
[markup.highlight]
noClasses = true
codeFences = true
guessSyntax = true
lineNos = true
lineNumbersInTable = false
style = "dracula"

[markup.goldmark.renderer]
unsafe = true

[services]
[services.rss]
limit = 24

[menu]
[[menu.main]]
identifier = "home"
name = "Home"
url = "/"
weight = 1

[[menu.main]]
identifier = "archive"
name = "Archive"
url = "/archive/"
weight = 2

[[menu.main]]
identifier = "series"
name = "Series"
url = "/series/"
weight = 3

[[menu.main]]
identifier = "category"
name = "Category"
url = "/categories/"
weight = 4

[[menu.main]]
identifier = "year"
name = "Year"
url = "#"
weight = 5

[[menu.main]]
parent = "year"
identifier = "2025"
name = "2025"
url = "/read/2025/"
weight = 1

[[menu.main]]
parent = "year"
identifier = "2024"
name = "2024"
url = "/read/2024/"
weight = 2


[params]
author = "BX"
description = "过度社会化是人类对彼此施加的最残忍之暴行"
keywords = "oversocialization"
img_home = "default/home.jpg"
img_404 = "default/404.webp"
useFaviconGenerator = true

[params.sidebar]
enable = true
avatar = "default/hakim.png"
bio = ""

[params.social]
twitter = "anastagizeno"
github = "anastagizeno"
gitlab = "anastagizeno"
linkedin = "anastagizeno"
rss = true

[[params.azeroth]]
name = "Kharanos"
url = "/dogdoor/janus/resume/%E5%BA%B7%E7%82%B3%E6%98%9F-%E6%9C%8D%E5%8A%A1%E7%AB%AF%E5%BC%80%E5%8F%91-%E4%B8%AA%E4%BA%BA%E7%AE%80%E5%8E%86.pdf"

[[params.azeroth]]
name = "Janus"
url = "/dogdoor/janus"

[[params.azeroth]]
name = "Ahau"
url = "/dogdoor/log/ahau"

[[params.azeroth]]
name = "Popol Vuh"
url = "/dogdoor/log/vuh"

[[params.azeroth]]
name = "Epictetus"
url = "/dogdoor/log/epictetus"

[[params.azeroth]]
name = "Seneca"
url = "/dogdoor/log/seneca"

[[params.azeroth]]
name = "Dephi"
url = "/dogdoor/page/delphi.html"

[[params.azeroth]]
name = "Stamford Bridge"
url = "/chelsea/"

[params.giscus]
enable = false
