baseURL = "https://shahrazad.fun"
title = "Shahrazad"
copyright = ""
paginate = 6
languageCode = "en"
defaultContentLanguage = "en"
hasCJKLanguage = true
enableInlineShortcodes = true
enableEmoji = true
ignoreErrors = ["error-remote-getjson"]
disableHugoGeneratorInject = true

[outputs]
home = ["HTML", "JSON", "RSS"]

[taxonomies]
category = "categories"
tag = "tags"
series = "series"

[markup]
[markup.highlight]
noClasses = true
codeFences = true
guessSyntax = true
lineNos = true
lineNumbersInTable = false
style = "dracula"

[markup.goldmark.renderer]
unsafe = true

[services]
[services.rss]
limit = 24

[menu]
[[menu.main]]
identifier = "home"
name = "Home"
url = "/"
weight = -1
[[menu.main]]
identifier = "archive"
name = "Archive"
url = "/archive/"
weight = 1
[[menu.main]]
identifier = "series"
name = "Series"
url = "/series/"
weight = 2
[[menu.main]]
identifier = "category"
name = "Category"
url = "/categories/"
weight = 3
[[menu.main]]
identifier = "read"
name = "2024"
url = "/read/2024/"
weight = 2024


[params]
author = "BX"
description = "守卫信仰，拯救苦难"
keywords = "personal"
notFoundPageTitle = "Dove è questo?"
img_home = "default/home.jpg"
img_404 = "default/404.webp"
useFaviconGenerator = true

[params.sidebar]
enable = true
avatar = "default/hakim.png"
bio = "别不好意思<br>别浪费时间"

[params.social]
twitter = "anastagizeno"
github = "anastagizeno"
gitlab = "anastagizeno"
linkedin = "anastagizeno"
rss = true

[[params.azeroth]]
name = "Kharanos"
url = "https://www.lizhinb.com/"

[[params.azeroth]]
name = "Iron Forge"
url = ""

[[params.azeroth]]
name = "Booty Bay"
url = "/dogdoor/katun/codice"

[[params.azeroth]]
name = "Stonefire Tavern"
url = "/dogdoor/katun/word"

[[params.azeroth]]
name = "Thunderbrew Distillery"
url = "/dogdoor/katun/note"

[params.giscus]
enable = false
