baseURL = "https://shahrazad.fun"
title = "Shahrazad"
copyright = ""
paginate = 6
languageCode = "en"
defaultContentLanguage = "en"
hasCJKLanguage = true
enableInlineShortcodes = true
enableEmoji = true
ignoreErrors = ["error-remote-getjson"]
disableHugoGeneratorInject = true

[outputs]
home = ["HTML", "JSON", "RSS"]

[taxonomies]
category = "categories"
tag = "tags"
series = "series"

[markup]
[markup.highlight]
noClasses = true
codeFences = true
guessSyntax = true
lineNos = true
lineNumbersInTable = false
style = "dracula"

[markup.goldmark.renderer]
unsafe = true

[services]
[services.rss]
limit = 24

[menu]
[[menu.main]]
identifier = "home"
name = "Home"
url = "/"
weight = -1
[[menu.main]]
identifier = "archive"
name = "Archive"
url = "/archive/"
weight = 1
[[menu.main]]
identifier = "series"
name = "Series"
url = "/series/"
weight = 2
[[menu.main]]
identifier = "category"
name = "Category"
url = "/categories/"
weight = 3
[[menu.main]]
identifier = "read"
name = "2025"
url = "/read/2025/"
weight = 2025


[params]
author = "BX"
description = "过度社会化是人类对彼此施加的最残忍之暴行"
keywords = "oversocialization"
notFoundPageTitle = "WE LOST"
img_home = "default/home.jpg"
img_404 = "default/404.webp"
useFaviconGenerator = true

[params.sidebar]
enable = true
avatar = "default/hakim.png"
bio = ""

[params.social]
twitter = "anastagizeno"
github = "anastagizeno"
gitlab = "anastagizeno"
linkedin = "anastagizeno"
rss = true

[[params.azeroth]]
name = "Kharanos"
url = "/dogdoor/ahau"

[[params.azeroth]]
name = "Iron Forge"
url = "/dogdoor/vuh"

[[params.azeroth]]
name = "WOW"
url = "/dogdoor/epictetus"

[[params.azeroth]]
name = "Booty Bay"
url = "https://www.lizhinb.com/"

[params.giscus]
enable = false
