baseURL = "https://anastagizeno.github.io/"
languageCode = "en-us"
title = "az1453"
theme = "hugo-nuo"
enableRobotsTXT = true
PygmentsCodeFences = true
canonifyurls = true
publishDir = "anastagizeno.github.io"

# Disqus Username
disqusShortname = "disqus_shortname"

# Google Analytics UA number
googleAnalytics = "UA-XXXXXXXX-X"

# Copyright of your post
copyright = "© This post is licensed under a Creative Commons Attribution-NonCommercial 4.0 International License，please give source if you wish to quote or reproduce."

# Initial site menu, you can extend menu with content.
[[menu.main]]
  name = "Home"
  weight = 10
  identifier = "home"
  url = "/"

[[menu.main]]
  name = "Archives"
  weight = 20
  identifier = "archives"
  url = "/archives/"

[[menu.main]]
  name = "Tags"
  weight = 30
  identifier = "tags"
  url = "/tags/"

# Add your own params here
[params]
  author = "__az1453"
  bg = "images/grey-prism.svg"
  avatar = "images/avatar.png"
  seotitle = "az1453"
  subtitle = ""
  description = ""
  paginate = 10

  # Choose your social networks
  email = "name@domain.com"
  github = "github_username"
  twitter = "twitter_username"
  # linkedin = "linkedin_username"
  # weibo = "weibo_username"
  # wechat= "images/qrcode.jpg"  # Replace with your wechat qrcode image
  # facebook = "facebook_username"
  # google = "googlplus_id_number"
  # instagram = "instagram_username"
  youtube = "youtube_username"
  # vimeo = "vimeo_username"
  medium = "medium_username"
  quora = "quora_username"
  # pinterest = "pinterest_username"
  # dribbble = "dribbble_username"
  # behance = "behance_username"
  # jsfiddle = "jsfiddle_username"
  # codepen = "codepen_username"
  # zhihu = "zhihu_username"
  # douban = "douban_username"
  # bilibili = "bilibili_id_number"
  stackoverflow = "douban_username"
  # codesandbox = ""
  # npm = ""
  # reddit = ""

  # Overrid theme styles in this file
  # customStyle = "styles/custom.scss"

  # Changyan Comments (China Only)
  #changyan = false
  #changyanId = ""
  #changyanConf = ""

  # Google Webmaster
  # https://www.google.com/webmasters/
  googleSiteVerification = "_moDmnnBNVLBN1rzNxyGUGdPHE20YgbmrtzLIbxaWFc"
