baseURL = "https://anastagizeno1453.com"
title = "Shahrazad"

# theme = ""

copyright = ""
paginate = 4
languageCode = "en"
defaultContentLanguage = "en"

hasCJKLanguage = true
enableInlineShortcodes = true
enableEmoji = true
# prevent build failures when using Hugo's Instagram shortcode due to deprecated Instagram API.
# See https://github.com/gohugoio/hugo/issues/7228#issuecomment-714490456
ignoreErrors = ["error-remote-getjson"]

disqusShortname = ""
googleAnalytics = ""

[outputs]
home = ["HTML", "JSON", "RSS"]

# prevent build failures when using Hugo's template _internal/opengraph.html
[taxonomies]
category = "categories"
tag = "tags"
series = "series"

[markup]
[markup.highlight]
noClasses = true
codeFences = true
guessSyntax = true
lineNos = true
lineNumbersInTable = false
style = "dracula"

[markup.goldmark.renderer]
unsafe = true

[menu]
[[menu.main]]
identifier = "home"
name = "Home"
url = "/"
weight = -100
[[menu.main]]
identifier = "archive"
name = "Archive"
url = "/archive/"
weight = 10
[[menu.main]]
identifier = "series"
name = "Series"
url = "/series/"
weight = 20
[[menu.main]]
identifier = "category"
name = "Category"
url = "/categories/"
weight = 30
[[menu.main]]
identifier = "about"
name = "2024"
url = "/about/"
weight = 40


[params]
author = "BX"
description = "守卫信仰，拯救苦难"
keywords = "personal"
notFoundPageTitle = "You lost"
img_home = "default/home.jpeg"
img_404 = "default/hadrian_trip.png"

useFaviconGenerator = true

custom_js = []
custom_css = [] # ["css/custom.css"]  Add your file to assets folder  [assets/css/custom.css]

[params.sidebar]
enable = false
gravatarEmail = ""
# Overwritten by your gravatar image if `gravatarEmail` is filled
avatar = "default/home.jpeg"
bio = "a personal website"

[params.social]
twitter = "anastagizeno"
facebook = "anastagizeno"
github = "anastagizeno"
gitlab = "anastagizeno"
linkedin = "anastagizeno"
rss = true
[params.social.mastodon]
weight = 56
icon = "fab fa-mastodon"
format = "https://mastodon.social/%v"
id = ""
url = ""

[[params.azeroth]]
name = "Kharanos"
url = "/404.html"

[[params.azeroth]]
name = "Iron Forge"
url = "/404.html"

[[params.azeroth]]
name = "Booty Bay"
url = "/404.html"

# See https://giscus.app/
[params.giscus]
enable = false
repo = ""
repo_id = ""
category = "General"
category_id = ""
input_position = "top"
theme = "light_tritanopia"
lang = "en"
